services:

  redis:
    image: redis:7.2
    container_name: seorang-redis
    ports:
      - "6379:6379"
    networks:
      - seorang-network

  app:
    build: .
    container_name: seorang-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - seorang-network

networks:
  seorang-network:
    driver: bridge