services:

  redis:
    image: redis:7.2
    container_name: seorang-redis
    ports:
      - "6379:6379"
    networks:
      - seorang-network

  app:
    build: .
    container_name: seorang-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    depends_on:
      - redis
    networks:
      - seorang-network

networks:
  seorang-network:
    driver: bridge